### ISSUE TITLE
Generate Participants Table Query

### ISSUE THREAD

**Issue by rebexxxxxx** [Analyticsphere/bq2#13]
Currently, the file [generate_bq2_queries.qmd] generates queries for many of the tables in GCP for BQ2. However the participants table is not included in the query generation, but the PII/Non PII variables are identified in the section "### Generate list of PII/non-PII variables from participants table". Please combine this section of the code with the section of the code which generates the queries for the remainder of the tables.

**Comment by jacobmpeters** [comment]
closing because this is addressed in #17
